### ISSUE TITLE
Improving playback mode

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/boats-animator#112]
There are a few things that I'd like to add to improve the frame reel area and playback. I may end up splitting this into multiple issues.
- [x] Additional playback controls #141
- [ ] Play / loop selection #116
- [x] Indication of current frame being played #115
- [x] Framereel scrollbar #163
## Additional playback controls

_Split out as #141_
As well as eventual keyboard shortcuts there should be buttons in the interface for previewing the previous and next frame relative to the currently selected one as well as buttons for jumping to the first and last frame captured. (basically buttons for `|<`, `<`, `>` and `>|`)

**Although:** I'm debating whether these require buttons as well keyboard shortcuts. I don't want the controls area getting too cluttered.
## Play / loop selection of captured frames

_Split out as #116_
After selecting a frame 3 more buttons (with keyboard shortcuts) will become available in the playback controls: (These will have icons) "Begin selection", "End selection" and "Unselect". 
- **Begin selection** - pressing this button after selecting a frame in the framereel will add a _blue?_ vertical line before it and means that after playback stops pressing play will start playback again from this point
  - If only "begin selection" is used then playback will run from the selected frame to the last frame.
- **End selection** - this button will be greyed out if "begin selection" hasn't been used yet. Selecting it will add a blue vertical line after it and mean that playback will run from the frame selected with "begin selection" to here.
  - If the frame selected with this tool is before the frame chosen with "begin selection" then playback will instead run from this frame to the "begin selection" frame.
- "Unselect" - as its name suggests, pressing this button removes both the start and end selection points
- The two selection points should eventually be draggable along the frame reel.
## Indication of current frame being played in the frame reel

_Split out as #115_
There should be a "position" arrow in the frame reel to indicate which frame is currently being played. The frame reel should scroll with this during playback. It should disappear after a frame is selected or when switching to capture mode.

I've currently been testing the positioner out and will create a pull request soon: 

<img width="904" alt="ba frameposition" src="https://cloud.githubusercontent.com/assets/8095888/12789326/3f8093c4-ca95-11e5-8e50-ebe114905bfe.png">
## Framereel scrollbar

_Split out as #163_
I implemented this is in a rush without properly consulting the other contributors to this project (This was also implemented before I knew how to use branches and PRs...), as a result I'll happily say it looks rather ugly!

It should be restyled with a darker background colour and probably be squarer.

Lots of ideas here, feedback is much appreciated!

**Comment by BoatsAreRockable** [comment]
Also I am pretty sure the way playback works by looping through img srcs is not at optimal. One potentially better way I can think of is loading all of the images stacked on top of each other in order using CSS's `z-index` and then playing them back by setting each one to `display: none`.

(I assume this is still not the most effective method...)

**Comment by le717** [comment]
For milestone tracking purposes, go ahead and break frame reel indicator section into a separate issue and assign it to the 0.6.x milestone, then add a link to it from here. Brain dump issues like this are good, but work on something begins/is nearly finished, it should be in its own issue.

**Comment by le717** [comment]
I just figured out how to best playback the captured images.

We currently display the video feed by drawing it to a `<canvas>`. Maybe you can figure it out from here. ;)

Basically, upon switching modes, we clear the canvas, pull the image data from `capturedFrames`, and draw it. Upon clicking play, we use `requestAnimationFrame`, throttled by the frame rate value, to loop through and draw the images to the canvas. When we are done and switch back to capture, clear canvas and restore the video stream.

Downside: RAF is capped at 60 FPS, per your browser's limit, but that is likely acceptable.

**Comment by BoatsAreRockable** [comment]
@le717 Not sure why I didn't reply to this before. 60 FPS seems an acceptable cap. I'd like to propose improving image playback is added to milestone 0.7.x since nwjs 0.13 isn't working well with the current playback method.

**Comment by BoatsAreRockable** [comment]
The only part of this issue left to implement is #116 and since it's a separate issue anyway I will go ahead and close this.
